Fix incorrect codegen on event fields with generic types
Cardinal-Cryptography/ink-wrapper pull request #60
Opened 2023-11-05 18:10 UTC by 0xnetfox

Hello :) hope Ya'll don't mind the PR, found this issue while applying ink-wrapper to one of my contracts

On the generation of code for an event with a field that mixed:

  1. Non-user defined generic (e.g. `Option<T>`)
  2. User-defined generic parameter (e.g. `T = CustomStruct`)

The generation fails to prefix the user-defined parameter with `super::`.

This can be seen in these tests I performed while debugging, given this event:

```rs
#[derive(scale::Decode, scale::Encode)]
#[cfg_attr(...)]
pub struct CustomId(u32);

#[derive(scale::Decode, scale::Encode)]
#[cfg_attr(...)]
pub struct CustomGeneric<T> {
    val: T
}

#[ink(event)]
pub struct SomeEvent {
    val1: Option<CustomId>,
    val2: CustomGeneric<CustomId>,
    val3: (CustomId, Option<CustomId>),
    val4: Vec<CustomId>,
    val5: Vec<Option<CustomId>>,
    val6: Result<u32, CustomId>,
}
```

ink-wrapper compiled using the main branch generated this code (errors explained in the comments):

```rs
#[derive(Debug, Clone, PartialEq, Eq, scale::Encode, scale::Decode)]
pub struct CustomId(pub u32);

#[derive(Debug, Clone, PartialEq, Eq, scale::Encode, scale::Decode)]
pub struct CustomGeneric {
    pub val: CustomId,
}

pub mod event {
    #[allow(dead_code, clippy::large_enum_variant)]
    #[derive(Debug, Clone, PartialEq, Eq, scale::Encode, scale::Decode)]
    pub enum Event {
        SomeEvent {
            val1: Option<CustomId>, // <- failed to prefix with super::,
            val2: super::CustomGeneric<super::CustomId>,
            val3: (super::CustomId, Option<CustomId>), // <- failed to prefix .1 with super::,
            val4: Vec<super::CustomId>,
            val5: Vec<Option<CustomId>>, // <- failed to prefix with super::,
            val6: Result<u32, CustomId>, // <- failed to prefix with super::,
        },
    }
}
```

and this is the generated code after applying this PR:

```rs
#[derive(Debug, Clone, PartialEq, Eq, scale::Encode, scale::Decode)]
pub struct CustomId(pub u32);

#[derive(Debug, Clone, PartialEq, Eq, scale::Encode, scale::Decode)]
pub struct CustomGeneric {
    pub val: CustomId,
}

pub mod event {
    #[allow(dead_code, clippy::large_enum_variant)]
    #[derive(Debug, Clone, PartialEq, Eq, scale::Encode, scale::Decode)]
    pub enum Event {
        SomeEvent {
            val1: Option<super::CustomId>,
            val2: super::CustomGeneric<super::CustomId>,
            val3: (super::CustomId, Option<super::CustomId>),
            val4: Vec<super::CustomId>,
            val5: Vec<Option<super::CustomId>>,
            val6: Result<u32, super::CustomId>,
        },
    }
}
```

The problem resided in the code assuming that if the generic was not custom, then its parameters were also not custom, which may not always be the case.

I'm not familiar w/ the codebase so I may have broken something else without realizing. But all the tests I performed resulted in correctly compiled code. Let me know if I missed anything :)

2023-11-08 12:39 UTC, obrok commented
Thanks for your contribution!

Please:

1. Add a test case that demonstrates the problem and fix. You can do that by adding your scenario to `test_contract`. In this case you shouldn't need to add any new test code, just having the test code generated from the test contract compile will be enough. You can check your work with `make all-dockerized`.
2. Reword your commit so that it starts with a capital letter.

2023-11-08 12:41 UTC, obrok requested changes
Thank you for your contribution!

Please:

1. Add a test case that demonstrates the problem and fix. You can do that by adding your scenario to `test_contract`. In this case you shouldn't need to add any new test code, just having the code generated from the test contract compile will be enough. You can check your work with `make all-dockerized`.
2. Reword your commit so that it starts with a capital letter.

(Reposting as review)

2023-11-09 18:14 UTC, 0xnetfox commented
There you go, added the base case to the tests and reworded the commit!

2023-11-13 12:54 UTC, obrok commented
Looks good, thanks!

2023-11-13 12:54 UTC, obrok approved these changes

2023-11-13 13:21 UTC, merged